name: Plugin Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 18
      uses: actions/setup-java@v4
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: 'maven'

    - name: Add SHORT_SHA env property
      run: echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV
    
    - name: Build with Maven
      run: |
        mvn -B clean package -DbuildNumber=${{ env.SHORT_SHA }}
      env:
        BUILD_NUMBER: '${{ env.SHORT_SHA }}'

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4.3.3
      with:
        name: 'KeepInventory build-${{ env.SHORT_SHA }}'
        path: target/*.jar